# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "NYTestApp.xcworkspace", scheme: "NYTestAppUITests")
  end
  lane :tests do
	scan(
  workspace: "NYTestApp.xcworkspace",
  scheme: "NYTestApp",
  output_directory: "fastlane/test_output/",
  clean: true,
  code_coverage: true,
  device: "iPhone 6s Plus",
  output_types: "html"
)
sh "slather coverage --ignore '../../*' \
  --html \
  --scheme NYTestApp \
  --workspace ../NYTestApp.xcworkspace \
  --output-directory test_output/code_coverage/ \
  ../NYTestApp.xcodeproj"
  end
end
